### ISSUE TITLE
Index error when running self-defined pytorch model

### ISSUE THREAD

**Issue by JacksonZyy** [Verified-Intelligence/alpha-beta-CROWN#21] opened 2023-02-21 09:59 UTC
Hi,

I am running abcrown on a self-defined pytorch model, where I replaced the `model_ori` as the following model, where all L_i are nn.Linear layers.:
```
class SVDNetBig(nn.Module):
    def __init__(self, L1, L2, L3, L4, L5, L6, L7):
        super(SVDNetBig, self).__init__()
        self.flatten = nn.Flatten()
        self.L1 = L1
        self.L1R = nn.ReLU(inplace = True)
        self.L2 = L2
        self.L2R = nn.ReLU(inplace = True)
        self.L3 = L3
        self.L3R = nn.ReLU(inplace = True)
        self.L4 = L4
        self.L4R = nn.ReLU(inplace = True)
        self.L5 = L5
        self.L5R = nn.ReLU(inplace = True)
        self.L6 = L6
        self.L6R = nn.ReLU(inplace = True)
        self.L7 = L7

    def forward(self, x):
        out = torch.sub(x, torch.tensor([[[[0.1307000070810318]]]], device = x.device))
        out = torch.div(out, torch.tensor([[[[0.30810001492500305]]]], device = x.device))
        out = self.flatten(out)
        out = self.L1(out)
        out = self.L1R(out)
        out = self.L2(out)
        out = self.L2R(out)
        out = self.L3(out)
        out = self.L3R(out)
        out = self.L4(out)
        out = self.L4R(out)
        out = self.L5(out)
        out = self.L5R(out)
        out = self.L6(out)
        out = self.L6R(out)
        out = self.L7(out)
        return out
```

The generated `BoundedModule` is defined as follows:
```
BoundedModule(
  (/0): BoundInput(name="/0")
  (/1): BoundParams(name="/1")
  (/2): BoundParams(name="/2")
  (/3): BoundParams(name="/3")
  (/4): BoundParams(name="/4")
  (/5): BoundParams(name="/5")
  (/6): BoundParams(name="/6")
  (/7): BoundParams(name="/7")
  (/8): BoundParams(name="/8")
  (/9): BoundParams(name="/9")
  (/10): BoundParams(name="/10")
  (/11): BoundParams(name="/11")
  (/12): BoundParams(name="/12")
  (/13): BoundParams(name="/13")
  (/14): BoundParams(name="/14")
  (/15): BoundConstant(name="/15")
  (/16): BoundSub(name="/16")
  (/17): BoundConstant(name="/17")
  (/18): BoundDiv(name="/18")
  (/19): BoundFlatten(name="/19")
  (/input): BoundLinear(name="/input")
  (/21): BoundRelu(name="/21")
  (/input.3): BoundLinear(name="/input.3")
  (/23): BoundRelu(name="/23")
  (/input.7): BoundLinear(name="/input.7")
  (/25): BoundRelu(name="/25")
  (/input.11): BoundLinear(name="/input.11")
  (/27): BoundRelu(name="/27")
  (/input.15): BoundLinear(name="/input.15")
  (/29): BoundRelu(name="/29")
  (/input.19): BoundLinear(name="/input.19")
  (/31): BoundRelu(name="/31")
  (/32): BoundLinear(name="/32")
)
```

However, calling `model.build_the_model()` gives me `IndexError`:
```
  File "/home/alpha-beta-CROWN/complete_verifier/auto_LiRPA/backward_bound.py", line 156, in backward_general
    A, lower_b, upper_b = l.bound_backward(l.lA, l.uA, *l.inputs)
  File "/home/alpha-beta-CROWN/complete_verifier/auto_LiRPA/operators/bivariate.py", line 562, in bound_backward
    uA_y = _bound_oneside(last_uA, y, sign=-1)
  File "/home/alpha-beta-CROWN/complete_verifier/auto_LiRPA/operators/bivariate.py", line 550, in _bound_oneside
    return self.broadcast_backward(sign * last_A, w)
  File "/home/alpha-beta-CROWN/complete_verifier/auto_LiRPA/operators/base.py", line 282, in broadcast_backward
    if shape[i] == 1 and A.shape[i + 1] != 1 and i != batch_dim:
IndexError: tuple index out of range
  File "/home/alpha-beta-CROWN/complete_verifier/auto_LiRPA/backward_bound.py", line 156, in backward_general
    A, lower_b, upper_b = l.bound_backward(l.lA, l.uA, *l.inputs)
  File "/home/alpha-beta-CROWN/complete_verifier/auto_LiRPA/operators/bivariate.py", line 562, in bound_backward
    uA_y = _bound_oneside(last_uA, y, sign=-1)
  File "/home/alpha-beta-CROWN/complete_verifier/auto_LiRPA/operators/bivariate.py", line 550, in _bound_oneside
    return self.broadcast_backward(sign * last_A, w)
  File "/home/alpha-beta-CROWN/complete_verifier/auto_LiRPA/operators/base.py", line 282, in broadcast_backward
    if shape[i] == 1 and A.shape[i + 1] != 1 and i != batch_dim:
IndexError: tuple index out of range
```
Any insights on how to solve the issue? Thank you so much for your reply!

**Comment by KaidiXu** [comment] 2023-02-21 23:32
It may be caused by the shape of the constant passed to torch.div() is not supported generally enough.
I guess it can be fixed by change `out = torch.div(out, torch.tensor([[[[0.30810001492500305]]]], device = x.device))`
to `out = torch.div(out, torch.tensor(0.30810001492500305, device = x.device))`

**Comment by JacksonZyy** [comment] 2023-02-22 04:47
@KaidiXu Thanks! It worked out now!
Then for a constant term like `[[[[0.49140000343322754]],[[ 0.482200026512146]],[[0.4465000033378601]]]]` with size `[1,3,1,1]`, how would you suggest me to change it to avoid the index error? Thank you!

**Closed** 2023-03-07 11:10 UTC
